### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by chklopp** [ldenti/klocate#1]
Hi,

I've indexed the example data using 
klocate index dros.4.fa
then aligned with
klocate find dros.4.fa query.k23.fa
and I got :
[M::bwa_idx_load_from_disk] read 0 ALT contigs
Index load.
Erreur du bus
after 2696320 lines 

Another test, I've extracted one sequence from the reference dros.4.fa 
>0
TTTTAATTTACTTAACATAGG
If I search this sequence with grep I find it once (kind of proxy to the real count because de reference fasta is multi-line) 
and the resulting output file contains 2696320 lines which is quite impossible.

**Comment by ldenti** [comment]
Hi,
can you please run:
```
./klocate find -f 1 dros.4.fa query.k23.fa
```
(note the `-f 1` argument to specify the query file format).

By default, the query file is expected to be a txt file (i.e., one kmer per line). Using `-f 1`, the query file is expected to be in fasta/q.

Let me know,
Luca

**Comment by chklopp** [comment]
Thank you. I thought that the default file format was fasta. It works now.

**Comment by ldenti** [comment]
Great!
